apiVersion: v1
kind: Service
metadata:
  name: node-backend-app-service
  namespace: backend-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: node-backend-app
  ports:
    - port: 80
      targetPort: 5152
      nodePort: 30008
